name: Tests

on:
  push:
    branches:
      - v-6.0.3

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['7.3', '7.4']
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Set up Docker
        run: |
          sudo rm /usr/local/bin/docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin
      - name: Start Docker container
        run: docker-compose up -d rabbitmq

      - name: docker ps
        run: docker-compose ps

      - name: Install dependencies
        run: |
          composer config --no-plugins allow-plugins.kylekatarnls/update-helper true
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose